---

network_name: Nokia
network_pass: XXXXXXXXXX

arch_root: /mnt
domain_suffix: gempi.re

kernel: linux-lts

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York

modprobe_modules:
  - tun
  - i2c-dev
  - uinput

initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - plymouth
  - modconf
  - block
  - sd-encrypt
  - lvm2
  - filesystems
  - fsck

pacstrap_packages:
  - base
  - "{{ kernel }}"
  - linux-firmware
  - ansible

base_packages:
  # system automation / maintinance
  #- ansible-core
  #- ansible
  - efibootmgr
  - pacman-contrib
  - fwupd
  - arch-install-scripts

  # bare system
  - base-devel
  - exfatprogs
  - ntfs-3g
  - dosfstools
  - lvm2
  - cryptsetup

  # audio
  - alsa-utils
  - pipewire
  - wireplumber
  - pipewire-audio
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack

  # netwoek
  - wpa_supplicant
  - networkmanager

  # WM
  - xorg
  - xorg-xinit

  # hardware
  - acpilight # BOSON ONLY laptop backlight
  - lm_sensors

  - plymouth # boot splash screen
  - sbctl # secure boot

  # system utilities
  - sudo
  - htop
  - tar
  - zip
  - unrar
  - unzip
  - inetutils
  - rsync

  # devel
  - tk
  - git
  - git-lfs
  - jdk-openjdk
  - docker
  - cmake
  - code
  - gvim
  - gdb
  - xterm
  - tmux
  - ntp
  - bc

  # python packages
  - python
  - pyenv
  - python3
  - python-pip
  - python-yaml
  - python-jinja
  - python-passlib
  - python-pre-commit
  - python-markupsafe

  # user utilities
  - wget
  - iwd
  - rtkit
  - libva-utils
  - cifs-utils
  - yt-dlp
  - xdotool
  - wmname
  - usbutils
  - strace
  - gtk3
  - eog
  - net-tools
  - unclutter
  - gvfs
  - feh
  - neofetch

  # applications
  - zsh
  - arandr
  - bspwm
  - sxhkd
  - rofi
  - flameshot
  - picom
  - alacritty
  - nitrogen
  - redshift
  - thunar
  - ranger
  # - inkscape
  # - gimp
  # - darktable
  # - kicad
  - mpc
  - ncmpcpp
  - dunst
  - firefox
  - vlc
  - bitwarden
  - bitwarden-cli
  - zathura
  - xournalpp
  - transmission-cli
  - transmission-gtk
  - polybar
  - pavucontrol
  - lxappearance-gtk3
  - baobab
  - calibre

  # security
  - clamav
  - rkhunter

  # extras
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - ttf-font-awesome
  - powerline-fonts
  - gnome-themes-extra

  # aur dependancies
  - go
  - rust
  - doas
  - perl-xml-parser
  - intltool
  - libcurl-gnutls

aur_base_packages:
  - yay
  - xp-pen-tablet
  # - picom-ibhagwan-git
  - piavpn-bin
  - brave-bin
  - cava
  - amdgpu_top
  # - sbctl-initcpio-post-hook
  # - plymouth-theme-owl-git
  # - cura
  # - ddccontrol-db-git
  # - ddccontrol
  # - spotify
  # - zenpower3-dkms
  # - zenmonitor
  # - python-detect-secrets

username: aryan

user:
  name: "{{ username }}"
  uid: 42069
  group: "{{ username }}"
  home_dir: "/home/{{ username }}"
  groups:
    - aryan
    - wheel
  shell: /usr/bin/zsh
  email:  me@theguptaempire.net

github_username: aryan-gupta

# project_dir: "{{ user.home_dir }}/Projects"
godfile_dir: "/godfile"

dotfile_repo: "dotfiles"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"

scripts_repo: "scripts"
scripts_repo_github: "https://github.com/{{ github_username }}/{{ scripts_repo }}"

life_folders_root: /data/life

life_folders:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"

aol0_folders:
  - unsorted

aol1_folders:
  - albums
  - entertainment
  - government
  - other-life
  - residency
  - tech
  - auto
  - financial
  - grad
  - outdoors
  - secrets
  - company
  - fitness
  - medical
  - professional
  - social

aol2_folders:
  - pass

aol3_folders:
  - pass

aol4_folders:
  - pass


delete_default_home_folders:
  - Desktop
  - Document
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos

# some apps require some home folders
# link them to the root of home
link_default_home_folders:
  - Desktop
  - Downloads
