---
arch_root: /mnt
domain_suffix: gempi.re

kernel: linux-lts

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York

pacstrap_packages:
  - base
  - linux-lts
  - linux-firmware
  - ansible

base_packages:
  # extensions
  - exfat-utils
  - ntfs-3g
  - lvm2

  # maintinance
  - pacman-contrib 
  - fwupd

  # devel
  - base-devel
  - zsh
  - ansible
  - jdk-openjdk
  - python3
  - docker
  - tar
  - zip

  # utilities
  - sudo
  - efibootmgr
  - wget
  - vim

  # applications
  - xorg
  - bspwm
  - sxhkd
  - rofi
  - flameshot
  - code
  - alacritty
  - nitrogen
  - redshift
  - inkscape
  - gimp
  - kicad
  - mpc
  - ncmpcpp
  - dunst

aur_base_packages:
  - polybar

username: aryan
home_dir: "/home/{{ username }}"
github_username: aryan-gupta

project_dir: "{{ home_dir }}/Projects"

dotfile_repo: "linux.files"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"