---

network_name: Nokia
network_pass: XXXXXXXXXX

arch_root: /mnt
domain_suffix: gempi.re

kernel: linux-lts

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York

pacstrap_packages:
  - base
  - linux-lts
  - linux-firmware
  - ansible

base_packages:
  # system automation / maintinance
  - ansible-core
  - ansible
  - efibootmgr
  - pacman-contrib
  - fwupd
  - arch-install-scripts

  # bare system
  - base-devel
  - exfatprogs
  - ntfs-3g
  - lvm2
  - cryptsetup
  - alsa-utils
  - pipewire
  - wireplumber
  - pipewire-audio
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - wpa_supplicant
  - networkmanager
  - xorg
  - xorg-xinit

  # system utilities
  - sudo
  - tar
  - zip
  - unrar
  - unzip
  - inetutils

  # devel
  - tk
  - git
  - git-lfs
  - jdk-openjdk
  - docker
  - cmake
  - code
  - gvim
  - gdb
  - xterm
  - tmux
  - ntp

  # python packages
  - python
  - python3
  - python-pip
  - python-yaml
  - python-jinja
  - python-passlib
  - python-pre-commit
  - python-markupsafe

  # user utilities
  - wget
  - iwd
  - rtkit
  - libva-utils
  - cifs-utils
  - youtube-dl
  - xdotool
  - wmname
  - usbutils
  - strace
  - gtk3
  - eog
  - net-tools
  - unclutter
  - gvfs

  # applications
  - zsh
  - arandr
  - bspwm
  - sxhkd
  - rofi
  - flameshot
  - picom
  - alacritty
  - nitrogen
  - redshift
  - thunar
  - ranger
  # - inkscape
  # - gimp
  # - darktable
  # - kicad
  - mpc
  - ncmpcpp
  - dunst
  - firefox
  - vlc
  - bitwarden
  - bitwarden-cli
  - zathura
  - xournalpp
  - transmission-cli
  - transmission-gtk
  - polybar
  - pavucontrol
  - lxappearance-gtk3
  - baobab
  - calibre

  # extras
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - ttf-font-awesome
  - powerline-fonts
  - gnome-themes-extra

  # aur dependancies
  - go
  - rust
  - doas
  - perl-xml-parser
  - intltool
  - libcurl-gnutls

aur_base_packages:
  - yay
  - xp-pen-tablet
  # - picom-ibhagwan-git
  - brave-bin
  - cava
  # - cura
  # - ddccontrol
  # - spotify

username: aryan

user:
  name: "{{ username }}"
  uid: 42069
  group: "{{ username }}"
  home_dir: "/home/{{ username }}"
  groups:
    - aryan
    - wheel
  shell: /usr/bin/zsh
  email:  me@theguptaempire.net

github_username: aryan-gupta

# project_dir: "{{ user.home_dir }}/Projects"
godfile_dir: "/godfile"

dotfile_repo: "dotfiles"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"

life_folders:
  - /life/0
  - /life/1
  - /life/2
  - /life/3
  - /life/4
