---

network_name: Nokia
network_pass: XXXXXXXXXX

arch_root: /mnt
domain_suffix: gempi.re

kernel: linux-lts

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York

pacstrap_packages:
  - base
  - linux-lts
  - linux-firmware
  - ansible

base_packages:
  # ansible / automation packages
  - ansible-core
  - ansible
  - efibootmgr
  - python
  - python-passlib
  - python-jinja
  - python-yaml
  - python-markupsafe

  # extensions
  - exfat-utils
  - ntfs-3g
  - lvm2

  # maintinance
  - pacman-contrib
  - fwupd

  # devel
  - base-devel
  - zsh
  - ansible
  - jdk-openjdk
  - python3
  - docker
  - tar
  - zip
  - unrar
  - unzip
  - cmake
  - code
  - gdb
  - xterm
  - tmux
  - python-pre-commit

  # utilities
  - sudo
  - efibootmgr
  - wget
  - vim
  - iwd
  - wpa_supplicant
  - networkmanager
  - python-passlib
  - alsa-utils
  - pipewire
  - wireplumber
  - pipewire-audio
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - rtkit
  - libva-utils
  - git
  - go
  - doas
  - cifs-utils
  - youtube-dl
  - xf86-input-wacom
  - xdotool
  - wmname
  - usbutils
  - strace
  - inetutils

  # applications
  - xorg
  - xorg-xinit
  - arandr
  - bspwm
  - sxhkd
  - rofi
  - flameshot
  - code
  - picom
  - alacritty
  - nitrogen
  - redshift
  - thunar
  - ranger
  # - inkscape
  # - gimp
  # - darktable
  # - kicad
  - mpc
  - ncmpcpp
  - dunst
  - firefox
  - vlc
  - bitwarden-cli
  - zathura
  - xournalpp
  - transmission-cli
  - transmission-gtk
  - polybar
  - pavucontrol
  - lxappearance-gtk3 
  
  # extra
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra 
  - ttf-font-awesome
  - powerline-fonts

aur_base_packages:
  - yay
  - xp-pen-tablet
  # - picom-ibhagwan-git
  - brave-bin
  - cava
  # - cura
  # - ddccontrol
  # - spotify

username: aryan

user:
  name: "{{ username }}"
  uid: 42069
  group: "{{ username }}"
  home_dir: "/home/{{ username }}"
  groups:
    - wheel
  shell: /usr/bin/zsh
  email:  me@theguptaempire.net

github_username: aryan-gupta

project_dir: "{{ user.home_dir }}/Projects"

dotfile_repo: "linux.files"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"