---
system_name: ArchLinux

username: aryan
github_username: aryan-gupta
email: "me@theguptaempire.net"

arch_root: /mnt

kernel: linux-lts
lvm_postfix: "_lv"
crypt_postfix: "_crypt"

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York
domain_suffix: gempi.re

modprobe_modules:
  - tun
  - i2c-dev
  - uinput

initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - plymouth
  - modconf
  - block
  - sd-encrypt
  - lvm2
  - filesystems
  - fsck

pacstrap_packages:
  - base
  - "{{ kernel }}"
  - python3 # so that ansible can run its code in the chroot
  - linux-firmware
  - ansible

base_packages:
  # system automation / maintinance
  - efibootmgr
  - pacman-contrib
  - fwupd
  - arch-install-scripts
  - archiso

  # hardware
  - lm_sensors
  - sof-firmware

  # system
  - exfatprogs
  - ntfs-3g
  - cifs-utils
  - dosfstools
  - lvm2
  - nfs-utils
  - cryptsetup
  - plymouth # boot splash screen
  - sbctl # secure boot
  - sudo
  - htop
  - ntp
  - gvfs
  - smartmontools

  # devel
  - base-devel
  - tk
  - git
  - git-lfs
  - jdk-openjdk
  - docker
  - cmake
  - code
  - gvim
  - gdb
  - rsync
  - xterm
  - tmux
  - bc
  - tar
  - zip
  - unrar
  - unzip
  - strace
  - usbutils

  # security
  - clamav
  - rkhunter

  # network
  - inetutils
  - wpa_supplicant
  - networkmanager
  - nm-connection-editor
  - iwd
  - net-tools

  # WM
  - xorg
  - xorg-xinit
  - xdotool
  - wmname
  - libva-utils
  - gtk3
  - arandr
  - bspwm
  - sxhkd

  # audio
  - rtkit
  - alsa-utils
  - pavucontrol
  - pipewire
  - wireplumber
  - pipewire-audio
  - pipewire-pulse
  - pipewire-alsa
  # - pipewire-jack # one day I will have a real time kernel and a sound room

  # python packages
  - python # who uses python 2 anymore?
  - pyenv
  - python3 # duplicate
  - python-pip
  - python-yaml
  - python-jinja
  - python-passlib
  - python-pre-commit
  - python-markupsafe

  # user utilities
  - wget
  - jq
  - yt-dlp
  - eog
  - unclutter
  - feh
  - neofetch
  - zsh
  - rofi
  - flameshot
  - picom
  - alacritty
  # - nitrogen
  - redshift
  - thunar
  - ranger
  # - inkscape
  # - gimp
  # - darktable
  # - kicad
  # - mpc
  # - ncmpcpp
  - dunst
  - firefox
  - vlc
  - bitwarden
  - bitwarden-cli
  - zathura
  - xournalpp
  - transmission-cli
  - transmission-gtk
  - polybar
  - lxappearance-gtk3
  - baobab
  - calibre
  - discord

  # extras
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - ttf-font-awesome
  - powerline-fonts
  - gnome-themes-extra

  # aur dependancies
  - go
  - rust
  - doas
  - perl-xml-parser
  - intltool
  - libcurl-gnutls

aur_base_packages:
  - yay
  - xp-pen-tablet
  - piavpn-bin
  - brave-bin
  - cava
  # - sbctl-initcpio-post-hook
  # - plymouth-theme-owl-git
  # - cura
  # - ddccontrol-db-git
  # - ddccontrol
  # - spotify
  # - zenpower3-dkms
  # - zenmonitor
  # - python-detect-secrets

user:
  name: "{{ username }}"
  uid: 42069
  group: "{{ username }}"
  home_dir: "/home/{{ username }}"
  groups:
    - "{{ username }}"
    - wheel
    - video
  shell: /usr/bin/zsh
  email:  "{{ email }}"

godfile_dir: "/godfile"
dotfile_repo: "dotfiles"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"
scripts_repo: "scripts"
scripts_repo_github: "https://github.com/{{ github_username }}/{{ scripts_repo }}"

life_folders_root: /data/life

life_folders:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"

aol0_folders:
  - unsorted

aol1_folders:
  - albums
  - entertainment
  - government
  - other-life
  - residency
  - tech
  - auto
  - financial
  - grad
  - outdoors
  - secrets
  - company
  - fitness
  - medical
  - professional
  - social

aol2_folders: []

aol3_folders: []

aol4_folders: []

delete_default_home_folders:
  - Desktop
  - Document
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos

# some apps require some home folders
# link them to the root of home
link_default_home_folders:
  - Desktop
  - Downloads
