---
username: aryan
github_username: aryan
email: "me@theguptaempire.net"

arch_root: /mnt
domain_suffix: gempi.re

kernel: linux-lts

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York


# system_name: ArchLinux

partitions:
  # index 0 must be esp/efi/boot partition
  - device: "{{ install_disk }}"
    flags: [ 'boot' ]
    name: efi
    number: 1
    start: 0%
    end: 512MiB
    label: ArchLinux
  - device: "{{ install_disk }}"
    flags: [  ]
    name: linux
    number: 2
    start: 512MiB
    end: 100%
    label: "{{ hostname }}_crypt"

# The first crypt device MUST be what contains root device
crypt:
  - device: "{{ install_disk }}{{ part_postfix }}2"
    name: "{{ partitions[1].label }}"
    type: luks2
    cipher: aes-xts-plain64
    keysize: 512
    hash: sha512
    passphrase: "{{ luks_password }}"
    keyfile_name: "{{ partitions[1].label }}_{{ ansible_date_time.date }}"
    keyfile: "/tmp/{{ partitions[1].label }}_{{ ansible_date_time.date }}"
    keyfile_len: 512

lvm_postfix: "_lv"
lvm:
  pv:
    - device: "/dev/mapper/{{ crypt[0].name }}"
  vg:
    - name: "{{ hostname }}{{ lvm_postfix }}"
      pvresize: yes
      pvs:
        - "/dev/mapper/{{ crypt[0].name }}"
  lv:
    - name: root
      vg: "{{ hostname }}{{ lvm_postfix }}"
      size: "{{ root_vol_size }}"
    - name: var
      vg: "{{ hostname }}{{ lvm_postfix }}"
      size: "{{ var_vol_size }}"
    - name: data
      vg: "{{ hostname }}{{ lvm_postfix }}"
      size: "{{ data_vol_size }}"
      #size: 100%FREE
    # - name: swap
    #   vg: "{{ hostname }}{{ lvm_postfix }}"
    #   size: 100%FREE

root:
  device: "/dev/mapper/{{ hostname }}{{ lvm_postfix }}-root"
  path: "/"
  chroot_path: "/mnt"
  fstype: ext4

mounts:
  # index 0 must be esp/efi/boot partition
  - device: "{{ install_disk }}{{ part_postfix }}1"
    path: "/efi"
    fstype: vfat
  - device: "/dev/mapper/{{ hostname }}{{ lvm_postfix }}-var"
    path: "/var"
    fstype: ext4
  - device: "/dev/mapper/{{ hostname }}{{ lvm_postfix }}-data"
    path: "/data"
    fstype: ext4

# I dont have a swap on my laptop since I dont want
# too many writes on my nvme flash. I have a script
# that warns me whenever I have filled up my RAM
# swap_part:


modprobe_modules:
  - tun
  - i2c-dev
  - uinput

initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - plymouth
  - modconf
  - block
  - sd-encrypt
  - lvm2
  - filesystems
  - fsck

pacstrap_packages:
  - base
  - "{{ kernel }}"
  - python3 # so that ansible can run its code in the chroot
  - linux-firmware
  - ansible

base_packages:
  # system automation / maintinance
  - efibootmgr
  - pacman-contrib
  - fwupd
  - arch-install-scripts

  # hardware
  - lm_sensors

  # system
  - base-devel
  - exfatprogs
  - ntfs-3g
  - dosfstools
  - lvm2
  - cryptsetup
  - efibootmgr
  - plymouth # boot splash screen
  - sbctl # secure boot

  # audio
  - alsa-utils
  - pipewire
  - wireplumber
  - pipewire-audio
  - pipewire-pulse
  - pipewire-alsa
  # - pipewire-jack # one day I will have a real time kernel and a sound room

  # network
  - wpa_supplicant
  - networkmanager

  # WM
  - xorg
  - xorg-xinit

  # system utilities
  - sudo
  - htop
  - tar
  - zip
  - unrar
  - unzip
  - inetutils
  - rsync

  # devel
  - tk
  - git
  - git-lfs
  - jdk-openjdk
  - docker
  - cmake
  - code
  - gvim
  - gdb
  - xterm
  - tmux
  - ntp
  - bc

  # python packages
  - python # who uses python 2 anymore?
  - pyenv
  - python3 # duplicate
  - python-pip
  - python-yaml
  - python-jinja
  - python-passlib
  - python-pre-commit
  - python-markupsafe

  # user utilities
  - wget
  - iwd
  - rtkit
  - libva-utils
  - cifs-utils
  - yt-dlp
  - xdotool
  - wmname
  - usbutils
  - strace
  - gtk3
  - eog
  - net-tools
  - unclutter
  - gvfs
  - feh
  - neofetch

  # applications
  - zsh
  - arandr
  - bspwm
  - sxhkd
  - rofi
  - flameshot
  - picom
  - alacritty
  - nitrogen
  - redshift
  - thunar
  - ranger
  # - inkscape
  # - gimp
  # - darktable
  # - kicad
  - mpc
  - ncmpcpp
  - dunst
  - firefox
  - vlc
  - bitwarden
  - bitwarden-cli
  - zathura
  - xournalpp
  - transmission-cli
  - transmission-gtk
  - polybar
  - pavucontrol
  - lxappearance-gtk3
  - baobab
  - calibre

  # security
  - clamav
  - rkhunter

  # extras
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - ttf-font-awesome
  - powerline-fonts
  - gnome-themes-extra

  # aur dependancies
  - go
  - rust
  - doas
  - perl-xml-parser
  - intltool
  - libcurl-gnutls

aur_base_packages:
  - yay
  - xp-pen-tablet
  # - picom-ibhagwan-git
  - piavpn-bin
  - brave-bin
  - cava
  - amdgpu_top
  # - sbctl-initcpio-post-hook
  # - plymouth-theme-owl-git
  # - cura
  # - ddccontrol-db-git
  # - ddccontrol
  # - spotify
  # - zenpower3-dkms
  # - zenmonitor
  # - python-detect-secrets

user:
  name: "{{ username }}"
  uid: 42069
  group: "{{ username }}"
  home_dir: "/home/{{ username }}"
  groups:
    - "{{ username }}"
    - wheel
  shell: /usr/bin/zsh
  email:  "{{ email }}"

godfile_dir: "/godfile"
dotfile_repo: "dotfiles"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"
scripts_repo: "scripts"
scripts_repo_github: "https://github.com/{{ github_username }}/{{ scripts_repo }}"

life_folders_root: /data/life

life_folders:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"

aol0_folders:
  - unsorted

aol1_folders:
  - albums
  - entertainment
  - government
  - other-life
  - residency
  - tech
  - auto
  - financial
  - grad
  - outdoors
  - secrets
  - company
  - fitness
  - medical
  - professional
  - social

aol2_folders: []

aol3_folders: []

aol4_folders: []

delete_default_home_folders:
  - Desktop
  - Document
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos

# some apps require some home folders
# link them to the root of home
link_default_home_folders:
  - Desktop
  - Downloads
