---

network_name: Nokia
network_pass: XXXXXXXXXX

arch_root: /mnt
domain_suffix: gempi.re

kernel: linux-lts

locales:
  - en_US.UTF-8
country: United States
timezone: America/New_York

pacstrap_packages:
  - base
  - linux-lts
  - linux-firmware
  - ansible

base_packages:
  # ansible / automation packages
  - ansible-core
  - ansible
  - git
  - efibootmgr
  - python
  - python-passlib
  - python-jinja
  - python-yaml
  - python-markupsafe

  # extensions
  - exfat-utils
  - ntfs-3g
  - lvm2

  # maintinance
  - pacman-contrib
  - fwupd

  # devel
  - base-devel
  - zsh
  - ansible
  - jdk-openjdk
  - python3
  - docker
  - tar
  - zip

  # utilities
  - sudo
  - efibootmgr
  - wget
  - vim
  - iwd
  - wpa_supplicant
  # - networkmanager
  - python-passlib
  - alsa-utils
  - pipewire
  - wireplumber
  - pipewire-audio
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - rtkit
  - libva-utils
  - git

  # applications
  - xorg
  - bspwm
  - sxhkd
  - rofi
  - flameshot
  - code
  - alacritty
  - nitrogen
  - redshift
  # - inkscape
  # - gimp
  # - kicad
  - mpc
  - ncmpcpp
  - dunst
  - firefox
  - vlc

aur_base_packages:
  - polybar

username: aryan

user:
  name: "{{ username }}"
  uid: 42069
  group: "{{ username }}"
  home_dir: "/home/{{ username }}"
  groups:
    - wheel
  shell: /usr/bin/zsh
  email:  me@theguptaempire.net

github_username: aryan-gupta

project_dir: "{{ user.home_dir }}/Projects"

dotfile_repo: "linux.files"
dotfile_repo_github: "https://github.com/{{ github_username }}/{{ dotfile_repo }}"