---
# This is the partition layout for typical install

partitions:
  # index 0 must be esp/efi/boot partition
  - device: "{{ install_disk }}"
    flags: [ 'boot' ]
    name: efi
    number: 1
    start: 0%
    end: 512MiB
    label: "{{ system_name }}"
  - device: "{{ install_disk }}"
    flags: [  ]
    name: linux
    number: 2
    start: 512MiB
    end: "{{ root_vol_size }}"
    label: "{{ hostname }}-root"
  - device: "{{ install_disk }}"
    flags: [  ]
    name: linux
    number: 3
    start: 512MiB
    end: "{{ var_vol_size }}"
    label: "{{ hostname }}-var"
  - device: "{{ install_disk }}"
    flags: [  ]
    name: linux
    number: 4
    start: 512MiB
    end: "{{ data_vol_size }}"
    label: "{{ hostname }}-data"

root:
  device: "{{ install_disk }}{{ part_postfix }}2"
  path: "/"
  chroot_path: "/mnt"
  fstype: ext4

mounts:
  # index 0 must be esp/efi/boot partition
  - device: "{{ install_disk }}{{ part_postfix }}1"
    path: "/efi"
    fstype: vfat
  - device: "{{ install_disk }}{{ part_postfix }}3"
    path: "/var"
    fstype: ext4
  - device: "{{ install_disk }}{{ part_postfix }}4"
    path: "/data"
    fstype: ext4

# I dont have a swap on my laptop since I dont want
# too many writes on my nvme flash. I have a script
# that warns me whenever I have filled up my RAM
# swap_part:
