---

- name: generate root hash pass
  command:  python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.encrypt('{{ root_password }}'))"
  register: hash
  tags:
    - user

- name: update root user password
  user:
    name: "root"
    password: '{{ hash.stdout }}'
  tags:
    - user

- name: generate user hash pass
  command:  python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.encrypt('{{ user_password }}'))"
  register: hash
  tags:
    - user

- name: create user group
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: create user and assign to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: '{{ hash.stdout }}'
    shell: "{{ user.shell }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups: "{{ user.groups }}"
    append: yes
  tags:
    - user

- name: configure sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# %wheel ALL=\(ALL:ALL\) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: visudo -cf %s

# - name: create life folder
#   ansible.builtin.file:
#     path: /home/life
#     state: directory
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: '0755'

- name: create getty folder
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: setup autologin
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    mode: 644
