---

secureboot_folders:
  - "{{ arch_root }}/usr/share/secureboot/"
  - "{{ arch_root }}/usr/share/secureboot/keys"
  # - "{{ arch_root }}/usr/share/secureboot/keys/PK"
  - "{{ arch_root }}/usr/share/secureboot/keys/KEK"
  - "{{ arch_root }}/usr/share/secureboot/keys/db"
  - "{{ arch_root }}/usr/share/secureboot/keys/dbx"

secureboot_files:
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/GUID"
    dst: "{{ arch_root }}/usr/share/secureboot/GUID"
  # - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/PK/PK.key"
  #   dst: "{{ arch_root }}/usr/share/secureboot/keys/PK/PK.key"
  # - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/PK/PK.pem"
  #   dst: "{{ arch_root }}/usr/share/secureboot/keys/PK/PK.pem"
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/KEK/KEK.key"
    dst: "{{ arch_root }}/usr/share/secureboot/keys/KEK/KEK.key"
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/KEK/KEK.pem"
    dst: "{{ arch_root }}/usr/share/secureboot/keys/KEK/KEK.pem"
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/db/db.key"
    dst: "{{ arch_root }}/usr/share/secureboot/keys/db/db.key"
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/db/db.pem"
    dst: "{{ arch_root }}/usr/share/secureboot/keys/db/db.pem"
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/dbx/dbx.key"
    dst: "{{ arch_root }}/usr/share/secureboot/keys/dbx/dbx.key"
  - src: "{{ secrets_repo_archiso_loc }}/secureboot/keys/dbx/dbx.pem"
    dst: "{{ arch_root }}/usr/share/secureboot/keys/dbx/dbx.pem"
