---
- hosts: localhost
  name: update Archlinux
  connection: local
  tags: ['install','backup', 'bootable']

  vars_files:
    - "group_vars/all_secret.yml"
    - "host_vars/{{ lookup('file', '/etc/hostname') }}.yml"

  roles:
  #  - role: 'backup'
  #  - role: 'bootable'
    - role: 'locale'
    - role: 'hosts'
    - role: 'packages'
      vars: { modes: [ 'clr', 'syu' ] } # clear and -Syu update
    - role: 'apps'
    - role: 'plymouth'
    - role: 'boot'
    - role: 'secureboot'
      when: 'secureboot == true'
    - role: 'accounts'
    - role: 'folders'
      vars: { mode: 'root' }

- hosts: localhost
  name: user setup
  become: true
  become_method: sudo
  connection: local
  become_user: "{{ user.name }}"
  tags: ['user']
  vars: { ansible_become_pass: "{{ user_password }}" }

  vars_files:
    - "group_vars/all_secret.yml"
    - "host_vars/{{ lookup('file', '/etc/hostname') }}.yml"

  roles:
    - role: 'dotfile'
      tags: 'dotfile'
    - role: 'folders'
      vars: { mode: "{{ user.name }}" }
    - role: 'user'
