---
- hosts: localhost
  name: update Archlinux
  connection: local
  tags: ['install','backup', 'bootable']

  pre_tasks:
    - include_vars: "group_vars/all_secret.yml"
    - include_vars: "host_vars/{{ ansible_hostname }}.yml"

  roles:
  #  - role: 'backup'
  #  - role: 'bootable'
    - role: 'locale'
    - role: 'hosts'
    - role: 'packages'
      vars: { modes: [ 'syu' ] }
    - role: 'apps'
    - role: 'plymouth'
    - role: 'boot'
    - role: 'secureboot'
      when: 'secureboot == true'
    - role: 'accounts'
    - role: 'folders'
      vars: { mode: 'root' }

- hosts: localhost
  name: user setup
  become: true
  become_method: sudo
  connection: local
  become_user: "{{ user.name }}"
  tags: ['user']
  vars: { ansible_become_pass: "{{ user_password }}" }

  pre_tasks:
    - include_vars: "group_vars/all_secret.yml"
    - include_vars: "host_vars/{{ ansible_hostname }}.yml"

  roles:
    - role: 'dotfile'
    - role: 'folders'
      vars: { mode: "{{ user.name }}" }
    - role: 'user'
