---
#- hosts: localhost
#  name: prepare system for reinstall
#  become: yes
#  connection: local
#  tags: ['backup', 'bootable']
#
#  roles:
#    - role: 'backup'
#    - role: 'bootable'

- hosts: localhost
  name: bootstrap ArchLinux system
  become: yes
  connection: local
  tags: ['pre']

  roles:
    - role: 'uefi'
    - role: 'disks'
    - role: 'pacstrap'
    - role: 'blobs'

- hosts: chroot
  name: install Archlinux
  connection: chroot
  tags: ['install']

  vars:
    hostname: hostvars['localhost']['hostname']

  roles:
    - role: 'locale'
    - role: 'hosts'
    - role: 'packages'
    - role: 'etc'
    - role: 'aur'
    - role: 'plymouth'
    - role: 'boot'
    - role: 'secureboot'
      when: "'default' not in {{ hostname }}" # dont run secureboot on VMs
    - role: 'accounts'
    - role: 'folders' # /home/aryan and /life
    - role: 'login'

- hosts: chroot
  name: user setup
  become: true
  become_method: sudo
  connection: chroot
  become_user: "{{ user.name }}"
  tags: ['user']

  roles:
    - role: 'user'
    - role: 'dotfile'
    # - role: 'life'
    - role: 'apps'
    # user config below
    #- role: 'firefox'
