---
#- hosts: localhost
#  name: prepare system for reinstall
#  become: yes
#  connection: local
#  tags: ['backup', 'bootable']
#
#  roles:
#    - role: 'backup'
#    - role: 'bootable'

- hosts: localhost
  name: bootstrap ArchLinux system
  become: yes
  connection: local
  tags: ['bootstrap']

  roles:
    - role: 'uefi'
    - role: 'part'
    - role: 'luks'
    - role: 'lvm'
    - role: 'fsmnt'
    - role: 'packages'
      vars: { modes: [ 'boot' ] }
    - role: 'blobs'

- hosts: chroot
  name: install Archlinux
  connection: chroot
  tags: ['install']

  roles:
    - role: 'locale'
    - role: 'hosts'
    - role: 'packages'
      vars: { modes: [ 'min', 'typ', 'aur' ] }
    - role: 'apps'
    - role: 'plymouth'
    - role: 'boot'
    - role: 'secureboot'
      when: '"default" not in hostname' # dont run secureboot on VMs
    - role: 'accounts'
    - role: 'folders' # /home/aryan and /life
      vars: { mode: 'root' }

- hosts: chroot
  name: user setup
  become: true
  become_method: sudo
  connection: chroot
  become_user: "{{ user.name }}"
  tags: ['user']

  roles:
    - role: 'dotfile'
    - role: 'folders'
      vars: { mode: "{{ user.name }}" }
    - role: 'user'
