---
#- hosts: localhost
#  name: prepare system for reinstall
#  become: yes
#  connection: local
#  tags: ['backup', 'bootable']
#
#  pre_tasks:
#    - include_vars: "host_vars/{{ hostname }}.yml"
#    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!
#
#  roles:
#    - role: 'backup'
#    - role: 'bootable'

- hosts: localhost
  name: bootstrap ArchLinux system
  become: yes
  connection: local
  tags: ['pre']

  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!

  roles:
    - role: 'uefi'
    # - role: 'internet'
    - role: 'ntp'
    - role: 'disks'
    - role: 'pacstrap'

- hosts: chroot
  name: install Archlinux
  connection: chroot
  tags: ['install']

  vars:
    hostname: hostvars['localhost']['hostname']

  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!

  roles:
    - role: 'locale'
    - role: 'hosts'
    - role: 'packages'
    - role: 'aur'
    - role: 'boot'
    - role: 'accounts'
    - role: 'folders' # /home/aryan and /life
    - role: 'login'

- hosts: localhost
  name: finish setup
  become: yes
  connection: local
  become_user: "{{ user.name }}"
  tags: ['user']

  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!

  roles:
    - role: 'user'
    - role: 'dotfile'
    - role: 'folders'
    # user config below
    #- role: 'firefox'
