---
- hosts: localhost
  name: prepare system for reinstall
  become: yes
  connection: local
  tags: ['backup', 'bootable']

  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!
  
  roles:
    - role: 'backup'
    - role: 'bootable'

- hosts: localhost
  name: bootstrap ArchLinux system
  become: yes
  connection: local
  tags: ['pre']
  
  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!
  
  roles:
    - role: 'pre'

- hosts: chroot
  name: install Archlinux
  connection: chroot
  tags: ['install', 'post']

  vars:
    hostname: hostvars['localhost']['hostname']

  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!

  roles:
    - role: 'install'
    - role: 'post'

- hosts: localhost
  name: finish setup
  become: yes
  connection: local
  tags: ['user']
  
  pre_tasks:
    - include_vars: "host_vars/{{ hostname }}.yml"
    - include_vars: "host_vars/{{ hostname }}_secret.yml" # WARNING: THIS NEEDS TO BE REMOVED AFTER TESTING!!
  
  roles:
    - role: 'user'