---
#- hosts: localhost
#  name: prepare system for reinstall
#  become: yes
#  connection: local
#  tags: ['backup', 'bootable']
#
#  roles:
#    - role: 'backup'
#    - role: 'bootable'

- hosts: localhost
  name: bootstrap ArchLinux system
  become: yes
  connection: local
  tags: ['bootstrap']

  pre_tasks:
    - include_vars: "extra_vars/disks.yml"
      when: '(nocrypt == false) and (nolvm == false)'
    - include_vars: "extra_vars/nocrypt.yml"
      when: '(nocrypt == true ) and (nolvm == false)'
    - include_vars: "extra_vars/nolvm.yml"
      when: '(nocrypt == false) and (nolvm == true )'
    - include_vars: "extra_vars/plain.yml"
      when: '(nocrypt == true ) and (nolvm == true )'

  roles:
    - role: 'uefi'
    - role: 'part'
      vars: { mode: 'plain' }
      when: '(nocrypt == true ) and (nolvm == true )'
    - role: 'part'
      vars: { mode: 'disk'  }
      when: 'nolvm == false'
    - role: 'luks'
    - role: 'lvm'
    - role: 'part'
      vars: { mode: 'luks'  }
      when: 'nolvm == true'
    - role: 'fsmnt'
    - role: 'packages'
      vars: { modes: [ 'boot' ] }
    - role: 'blobs'

- hosts: chroot
  name: install Archlinux
  connection: chroot
  tags: ['install']

  roles:
    - role: 'locale'
    - role: 'hosts'
    - role: 'packages'
      vars: { modes: [ 'min', 'typ', 'aur' ] }
    - role: 'apps'
    - role: 'plymouth'
    - role: 'boot'
    - role: 'secureboot'
      when: 'secureboot == true'
    - role: 'accounts'
    - role: 'folders'
      vars: { mode: 'root' }

- hosts: chroot
  name: user setup
  become: true
  become_method: sudo
  connection: chroot
  become_user: "{{ user.name }}"
  tags: ['user']

  roles:
    - role: 'dotfile'
    - role: 'folders'
      vars: { mode: "{{ user.name }}" }
    - role: 'user'
