---
# @TODO parameterize this
- name: set firefox as default browser
  ansible.builtin.command: "xdg-settings set default-web-browser firefox.desktop"

- name: remove default home folders
  ansible.builtin.file:
    state: absent
    path: "/home/{{ user.name }}/{{ item }}"
  loop: "{{ delete_default_home_folders }}"

- name: link required default home folders
  file:
    src: "/home/{{ user.name }}/"
    dest: "/home/{{ user.name }}/{{ item }}"
    state: link
    force: yes
  loop: "{{ link_default_home_folders }}"
