---
- name: install base packages
  pacman:
    name: "{{ base_packages }}"
    extra_args: --needed

- name: install packages
  pacman:
    name: "{{ packages }}"
    extra_args: --needed

- name: enable NetworkManager
  ansible.builtin.systemd:
    enabled: true
    name: NetworkManager.service

- name: enable ntpd
  ansible.builtin.systemd:
    enabled: true
    name: ntpd.service
