---

- name: "Installs base system using pacstrap"
  command: "/usr/bin/pacstrap {{ arch_root }} {{ pacstrap_packages | join(' ') }}"
  when: "'boot' in modes"

- name: "Populates base system fstab with configured storage devices"
  shell: "/usr/bin/genfstab -U -p {{ arch_root }} >> {{ arch_root }}/etc/fstab"
  # args: # there is already a fstab created and uncommenting this will cause ansible to skip this task
  #   creates: "{{ arch_root }}/etc/fstab"
  when: "'boot' in modes"

- name: create backup of mirrors
  shell: "cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig"
  args:
    creates: "/etc/pacman.d/mirrorlist.orig"
  when: "'mir' in modes"

- name: uncomment list of mirrors
  shell: "sed 's/^#Server/Server/' /etc/pacman.d/mirrorlist.orig > /etc/pacman.d/mirrorlist.all"
  args:
    creates: "/etc/pacman.d/mirrorlist.all"
  when: "'mir' in modes"

- name: rank mirrorts based off speed
  shell: "/usr/bin/rankmirrors -n 6 /etc/pacman.d/mirrorlist.all > /etc/pacman.d/mirrorlist"
  when: "'mir' in modes"

- name: clean pacman cache
  command:
    cmd: "paccache -rk{{ paccache_keep_num }}"
  when: "'clr' in modes"

- name: Upgrade system to latest state
  pacman:
    update_cache: yes
    upgrade: yes
  when: "'syu' in modes"

- name: install base packages
  pacman:
    name: "{{ base_packages }}"
    extra_args: --needed
  when: "'min' in modes"

- name: install packages
  pacman:
    name: "{{ packages }}"
    extra_args: --needed
  when: "'typ' in modes"

- name: allow unpriv sudoers
  copy:
    dest: "/etc/sudoers.d/tmp-{{ user.name }}-nopasswd"
    content: "{{ user.name }} ALL=(ALL:ALL) NOPASSWD: ALL" # pragma: allowlist secret
  when: "'aur' in modes"

- name: clone yay repo
  ansible.builtin.git:
    clone: yes
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/var/tmp/yay"
  when: "'aur' in modes"

- name: set yay folder permissions
  file:
    dest: "/var/tmp/yay"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '777'
    recurse: yes
  when: "'aur' in modes"

- name: build yay package
  ansible.builtin.command:
    cmd: "sudo -u {{ user.name }} makepkg -s --noconfirm --needed"
    chdir: "/var/tmp/yay"
  when: "'aur' in modes"

- name: get yay package names
  find:
    paths: "/var/tmp/"
    patterns: "*.pkg.*"
    file_type: "file"
    recurse: true
    depth: 2
  register: install_package
  when: "'aur' in modes"

- name: install yay
  pacman:
    name: "{{ item.path }}"
    state: present
  loop: "{{ install_package.files }}"
  when: "'aur' in modes"

# @TODO fix this so cache is spared
- name: install aur packages
  ansible.builtin.command:
    cmd: "sudo -u {{ user.name }} yay --noconfirm -S {{ item }}"
  loop: "{{ aur_base_packages }}"
  when: "'aur' in modes"

- name: remove {{ user.name }} sudoers file
  file:
    dest: "/etc/sudoers.d/tmp-{{ user.name }}-nopasswd"
    state: absent
  when: "'aur' in modes"
