---
- name: install base packages
  pacman:
    name: "{{ base_packages }}"
    extra_args: --needed

- name: install packages
  pacman:
    name: "{{ packages }}"
    extra_args: --needed

- name: enable NetworkManager
  ansible.builtin.systemd:
    enabled: true
    name: NetworkManager.service

- name: enable ntpd
  ansible.builtin.systemd:
    enabled: true
    name: ntpd.service

- name: mask accessibility service
  ansible.builtin.systemd:
    enabled: false
    masked: true
    name: at-spi-dbus-bus.service
    scope: "global" # "user" # "system"
      #  ignore_errors: true

- name: enable fresh clamav
  ansible.builtin.systemd:
    enabled: true
    name: clamav-freshclam.service