---
root_superblock: "{{ install_disk }}{{ part_postfix }}2"

boot_postfix: "{{            (0 | int)     if nolvm == true else (1 | int) }}"
root_postfix: "{{ (boot_postfix | int + 1) if nolvm == true else  '-root'  }}"
var_postfix:  "{{ (root_postfix | int + 1) if nolvm == true else  '-var'   }}"
data_postfix: "{{ ( var_postfix | int + 1) if nolvm == true else  '-data'  }}"

pre_disk: >-
  {{
    install_disk
    if (nocrypt == true ) and (nolvm == true ) else
    ('/dev/mapper/' + hostname)
  }}

dev_postfix: >-
  {{
    lvm_postfix
    if nolvm == false else
    part_postfix
    if nocrypt == true else
    crypt_postfix
  }}

root:
  device: "{{ pre_disk }}{{ dev_postfix }}{{ root_postfix }}"
  path: "/"
  chroot_path: "/mnt"
  fstype: ext4

mounts:
  # index 0 must be esp/efi/boot partition
  - device: "{{ install_disk }}{{ part_postfix }}1"
    path: "/efi"
    fstype: vfat
  - device: "{{ pre_disk }}{{ dev_postfix }}{{ var_postfix }}"
    path: "/var"
    fstype: ext4
  - device: "{{ pre_disk }}{{ dev_postfix }}{{ data_postfix }}"
    path: "/data"
    fstype: ext4

# I dont have a swap on my laptop since I dont want
# too many writes on my nvme flash. I have a script
# that warns me whenever I have filled up my RAM
# swap_part:
