---
- name: create secure folder on data drive
  file:
    path: "{{ arch_root }}/data/secure"
    state: directory

- name: copy encryption key into root partition
  copy:
    src: "{{ item.keyfile }}"
    dest: "{{ arch_root }}/data/secure/{{ item.keyfile_name }}"
  with_items: "{{ crypt }}"

- stat: path="{{ secureboot_keytarpacket.src }}"
  register: optional_file

- name: create secureboot directory
  file:
    path: "{{ secureboot_keytarpacket.unzippath }}"
    state: 'directory'
  when: optional_file.stat.exists
  ignore_errors: True

- name: copy secureboot file into chroot
  copy:
    src: "{{ secureboot_keytarpacket.src }}"
    dest: "{{ arch_root }}/{{ secureboot_keytarpacket.dest }}"
    owner: root
    group: root
  when: optional_file.stat.exists
  ignore_errors: True
