---
- name: create secure folder on data drive
  file:
    path: "{{ arch_root }}/data/secure"
    state: directory

- name: copy encryption key into root partition
  copy:
    src: "{{ item.keyfile }}"
    dest: "{{ arch_root }}/data/secure/{{ item.keyfile_name }}"
  with_items: "{{ crypt }}"
  when: nocrypt == false

- name: create secureboot directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ secureboot_folders }}"

- name: copy secureboot file into chroot
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: '0400'
    remote_src: true
  with_items:
    - "{{ secureboot_files }}"

- name: copy certificate authority file into chroot
  copy:
    src: "{{ secrets_repo_archiso_loc }}/certificate-authority/ca-chain.cert.pem"
    dest: "{{ arch_root }}/data/secure/ca-chain.cert.pem"
    remote_src: true

- name: copy public gnupg keys into chroot
  copy:
    src: "{{ secrets_repo_archiso_loc }}/gnupg/{{ item }}.pub.asc"
    dest: "{{ arch_root }}/data/secure/{{ item }}.pub.asc"
    remote_src: true
  with_items: "{{ gpg[hostname]['public'] }}"

- name: copy public gnupg keys into chroot
  copy:
    src: "{{ secrets_repo_archiso_loc }}/gnupg/{{ item }}.sub.key.asc"
    dest: "{{ arch_root }}/data/secure/{{ item }}.sub.key.asc"
    remote_src: true
  with_items: "{{ gpg[hostname]['private'] }}"
