---
- name: create secure folder on data drive
  file:
    path: "{{ arch_root }}/data/secure"
    state: directory

- name: copy encryption key into root partition
  copy:
    src: "{{ item.keyfile }}"
    dest: "{{ arch_root }}/data/secure/{{ item.keyfile_name }}"
  with_items: "{{ crypt }}"
  when: nocrypt == false

- name: create secureboot directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ arch_root }}/usr/share/secureboot/"
    - "{{ arch_root }}/usr/share/secureboot/keys"
    - "{{ arch_root }}/usr/share/secureboot/keys/PK"
    - "{{ arch_root }}/usr/share/secureboot/keys/KEK"
    - "{{ arch_root }}/usr/share/secureboot/keys/db"
    - "{{ arch_root }}/usr/share/secureboot/keys/dbx"

- name: copy secureboot file into chroot
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: '0400'
    remote_src: true
  with_items:
    - src: "ansible-secrets/secureboot/GUID"
      dst: "{{ arch_root }}/usr/share/secureboot/GUID"
    - src: "ansible-secrets/secureboot/keys/KEK/KEK.key"
      dst: "{{ arch_root }}/usr/share/secureboot/keys/KEK/KEK.key"
    - src: "ansible-secrets/secureboot/keys/KEK/KEK.pem"
      dst: "{{ arch_root }}/usr/share/secureboot/keys/KEK/KEK.pem"
    - src: "ansible-secrets/secureboot/keys/db/db.key"
      dst: "{{ arch_root }}/usr/share/secureboot/keys/db/db.key"
    - src: "ansible-secrets/secureboot/keys/db/db.pem"
      dst: "{{ arch_root }}/usr/share/secureboot/keys/db/db.pem"
    - src: "ansible-secrets/secureboot/keys/dbx/dbx.key"
      dst: "{{ arch_root }}/usr/share/secureboot/keys/dbx/dbx.key"
    - src: "ansible-secrets/secureboot/keys/dbx/dbx.pem"
      dst: "{{ arch_root }}/usr/share/secureboot/keys/dbx/dbx.pem"

- name: copy certificate authority file into chroot
  copy:
    src: "ansible-secrets/certificate-authority/ca-chain.cert.pem"
    dest: "{{ arch_root }}/data/secure/ca-chain.cert.pem"
    remote_src: true
