---
- name: load modules boot
  copy:
    dest: "/etc/modules-load.d/load-{{ item }}.conf"
    content: "{{ item }}"
  loop: "{{ modprobe_modules }}"

- name: allow restart script nopasswd
  copy:
    dest: "/etc/sudoers.d/restart-windows-nopasswd"
    content: "{{ user.name }} ALL = (root) NOPASSWD: /usr/bin/restart_into_windows.sh"

- name: allow xp pentablet nopasswd
  copy:
    dest: "/etc/sudoers.d/xppentablet-nopasswd"
    content: "{{ user.name }} ALL = (root) NOPASSWD: /usr/lib/pentablet/pentablet.sh"

# @TODO BETTER WAY TO HANDLE SCRIPTS
- name: link game mode script
  ansible.builtin.file:
    src: "{{ godfile_dir }}/{{ scripts_repo }}/nix/game_mode/restart_into_windows.sh"
    dest: "/usr/bin/restart_into_windows.sh"
    state: link
    force: true

- name: Creates firefox policies directory
  file:
    path: /etc/firefox/policies
    state: directory
    recurse: yes

- name: copy firefox policies file
  template:
    src: policies.json
    dest: /etc/firefox/policies
    mode: 644
