---
- name: allow nobody sudoers
  copy:
    dest: "/etc/sudoers.d/tmp-nobody-nopasswd"
    content: "nobody ALL=(ALL:ALL) NOPASSWD: ALL"

- name: clone yay repo
  ansible.builtin.git:
    clone: yes
    repo: "https://aur.archlinux.org/{{ item }}.git"
    dest: "/var/tmp/{{ item }}"
  loop: "{{ aur_base_packages }}"

- name: set folder permissions
  file:
    dest: "/var/tmp/{{ item }}"
    owner: nobody
    group: nobody
    mode: '777'
    recurse: yes
  loop: "{{ aur_base_packages }}"

- name: build aur packages
  ansible.builtin.command:
    cmd: "sudo -u nobody HOME=/tmp makepkg -s --noconfirm --needed"
    chdir: "/var/tmp/{{ item }}"
  loop: "{{ aur_base_packages }}"

- name: get package names
  find:
    paths: "/var/tmp/"
    patterns: "*.pkg.*"
    file_type: "file"
    recurse: true
    depth: 2
  register: install_package

- name: install aur packages
  pacman:
    name: "{{ item.path }}"
    state: present
  loop: "{{ install_package.files }}"

    #- name: install aur packages
    #  ansible.builtin.command:
    #    cmd: "yay --noconfirm -S {{ item }}"
    #  loop: "{{ aur_base_packages }}"
