---
# @TODO do not use date_time for keyfile nameing
# use the UUID of the disk or crypt partition
crypt:
  - device: "{{ install_disk }}{{ part_postfix }}2"
    name: "{{ hostname + crypt_postfix }}"
    type: luks2
    cipher: aes-xts-plain64
    keysize: 512
    hash: sha512
    passphrase: "{{ luks_password }}"
    keyfile_name: "{{ hostname + crypt_postfix }}_backup.keyfile"
    keyfile: "/tmp/{{ hostname + crypt_postfix }}_backup.keyfile"
    keyfile_len: 64
