---
- name: Create on disk partitions
  community.general.parted:
    state: present
    device: "{{ item.device }}"
    label: gpt
    flags: "{{ item.flags }}"
    name: "{{ item.name }}"
    number: "{{ item.number }}"
    part_start: "{{ item.start }}"
    part_end: "{{ item.end }}"
  with_items: "{{ partitions }}"
  when: "mode == 'disk'"

- name: Create on crypt partitions
  community.general.parted:
    state: present
    device: "{{ item.device }}"
    label: gpt
    flags: "{{ item.flags }}"
    name: "{{ item.name }}"
    number: "{{ item.number }}"
    part_start: "{{ item.start }}"
    part_end: "{{ item.end }}"
  with_items: "{{ crypt_partitions }}"
  when: "(nolvm == true) and (mode == 'luks')"

- name: Create on raw partitions
  community.general.parted:
    state: present
    device: "{{ item.device }}"
    label: gpt
    flags: "{{ item.flags }}"
    name: "{{ item.name }}"
    number: "{{ item.number }}"
    part_start: "{{ item.start }}"
    part_end: "{{ item.end }}"
  with_items: "{{ plain_partitions }}"
  when: "(nolvm == true) and (nocrypt == true) and (mode == 'plain')"
