---
- name: create getty folder
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: setup autologin
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    mode: 644
