---
- name: Copy network config file
  copy:
    src: nokia-netctl.conf
    dest: /etc/netctl/nokia

- name: Start netctl
  command: netctl start nokia

- name: Test network access
  net_ping: 
    dest: 8.8.8.8
  register: ping

- name: Fail if no network access
  fail:
    msg: "No network access!"
  when: ping.ping.count > 1

- name: Check internet connectivity
  wait_for:
    host: archlinux.org
    port: 80