---
- name: include vars from fsmnt
  include_vars: roles/fsmnt/defaults/main.yml
  tags: 'always'
# needed_vars:
# mounts[0].path

- name: sign efi binary
  ansible.builtin.command:
    cmd: "sbctl sign -s {{ mounts[0].path }}/{{ hostname }}-arch-{{ kernel }}-default.efi"
    chdir: "/efi"

- name: verify efi binary
  shell:
    cmd: "ESP_PATH=/efi sbctl verify | grep -q '✓ {{ mounts[0].path }}/{{ hostname }}-arch-{{ kernel }}-default.efi is signed'"
    chdir: "/efi"
  register: sb_verify_result
  failed_when: sb_verify_result.rc != 0
  changed_when: false
  tags:
    - sb-verify
