---
hostname: 'boson'

install_disk: "/dev/disk/by-id/nvme-WDC_PC_SN730_SDBQNTY-512G-1001_21081F804906"
part_postfix: "-part"

boot_vol_size: 512M
root_vol_size: 64G
var_vol_size: 16G
data_vol_size: 390G

nocrypt: false
nolvm: false
secureboot: false

initramfs_modules:
  - i915

packages:
  - intel-media-driver
  - intel-gpu-tools
  # - acpilight
  - nvme-cli
  - upower

host_user_groups: []

aur_packages: []

cpu_manufacturer: intel
