crypt_name: "{{ hostname }}_crypt"

# luks_keyfile_sha1sum: 9afcf147207d3edce1efb88b4260a56151403a1c

partitions:
  - device: /dev/nvme0n1
    flags: [ 'boot' ]
    name: efi
    number: 1
    start: 0%
    end: 512MiB

  - device: /dev/nvme0n1
    flags: [  ]
    name: linux
    number: 2
    start: 512MiB
    end: 100%

# The first crypt device MUST be what contains root device
crypt:
  - device: /dev/nvme0n1p2
    name: "{{ crypt_name }}"
    type: luks2
    cipher: aes-xts-plain64
    keysize: 512
    hash: sha512
    passphrase: "{{ luks_password }}"
    keyfile_name: "{{ luks_keyfile.file }}"
    keyfile: "{{ luks_keyfile.filepath }}"
    keyfile_len: 512

lvm:
  pv:
    - device: "/dev/mapper/{{ crypt_name }}"
  vg:
    - name: "{{ hostname }}_lvg01"
      pvresize: yes
      pvs:
        - "/dev/mapper/{{ crypt_name }}"
  lv:
    # nvme0n1                259:0    0 476.9G  0 disk
    # ├─nvme0n1p1            259:1    0   511M  0 part  /efi
    # └─nvme0n1p2            259:2    0 476.4G  0 part
    #   └─boson_crypt        254:0    0 476.4G  0 crypt
    #     ├─boson_lvg01-root 254:1    0    64G  0 lvm   /
    #     ├─boson_lvg01-var  254:2    0     8G  0 lvm   /var
    #     └─boson_lvg01-data 254:4    0   398G  0 lvm   /data
    - name: root
      vg: "{{ hostname }}_lvg01"
      size: 64G
    - name: var
      vg: "{{ hostname }}_lvg01"
      size: 8G
    # - name: home
    #   vg: "{{ hostname }}_lvg01"
    #   size: 128M
    - name: data
      vg: "{{ hostname }}_lvg01"
      size: 398G
      #size: 100%FREE
    # - name: swap
    #   vg: "{{ hostname }}_lvg01"
    #   size: 100%FREE

fs:
  - device: /dev/nvme0n1p1
    fstype: vfat
  - device: "/dev/mapper/{{ hostname }}_lvg01-root"
    fstype: ext4
  # - device: "/dev/mapper/{{ hostname }}_lvg01-home"
  #   fstype: ext4
  - device: "/dev/mapper/{{ hostname }}_lvg01-var"
    fstype: ext4
  - device: "/dev/mapper/{{ hostname }}_lvg01-data"
    fstype: ext4

root_part:
  device: /dev/mapper/{{ hostname }}_lvg01-root
  fstype: ext4

# I dont have a swap on my laptop since I dont want
# too many writes on my nvme flash. I have a script
# that warns me whenever I have filled up my RAM
# swap_part

mounts:
  - device: /dev/nvme0n1p1
    path: "/efi"
    fstype: vfat
  - device: "/dev/mapper/{{ hostname }}_lvg01-var"
    path: "/var"
    fstype: ext4
  # - device: "/dev/mapper/{{ hostname }}_lvg01-home"
  #   path: "/home"
    fstype: ext4
  - device: "/dev/mapper/{{ hostname }}_lvg01-data"
    path: "/data"
    fstype: ext4

initramfs_modules:
  - i915

packages:
  # - cura
  - sof-firmware
  - intel-media-driver
  - intel-gpu-tools

boot:
  device: /dev/nvme0n1p1
  mount: /efi
  part: 1
  label: ArchLinux

cpu_manufacturer: intel
