---

hostname: 'default'
install_disk: "/dev/vda"
root_vol_size: 10G
var_vol_size: 9G
data_vol_size: 128M
part_postfix: ""

initramfs_modules: []

# this var cannot be []. The script will fail with nothing but
#         TASK [packages : install packages] *********************************************************************************************************************************************************************************
#         fatal: [/mnt]: FAILED! => {"changed": false, "msg": "This is a bug"}
packages:
  - base

# only intel and amd are valid. All others are ignored
# and no ucode will be installed
cpu_manufacturer: default
