---

hostname: 'default'

install_disk: "/dev/vda"
part_postfix: ""

boot_vol_size: 512M
root_vol_size: 10G
var_vol_size: 8G
data_vol_size: 1G

nocrypt: false
nolvm: false
secureboot: true

initramfs_modules: []

packages:
  - qemu-guest-agent

host_user_groups: [] # any extra groups needed by the user on this host

# only intel and amd are valid. All others are ignored
# and no ucode will be installed
cpu_manufacturer: null
