---

hostname: 'default'
install_disk: "/dev/vda"
root_vol_size: 13G
var_vol_size: 5G
data_vol_size: 1G
part_postfix: ""

initramfs_modules: []
packages: []

# only intel and amd are valid. All others are ignored
# and no ucode will be installed
cpu_manufacturer: default
