crypt_name: "{{ hostname }}_crypt"

partitions:
  - device: /dev/sda
    flags: [ 'boot' ]
    name: boot
    number: 1
    start: 0%
    end: 512MiB

  - device: /dev/sda
    flags: [  ]
    name: linux
    number: 2
    start: 512MiB
    end: 100%

# The first crypt device MUST be what contains root device
crypt:
  - device: /dev/sda2
    name: "{{ crypt_name }}"
    type: luks2
    cipher: aes-xts-plain64
    keysize: 512
    hash: sha512
    passphrase: "{{ luks_password }}"
    keyfile_name: "{{ crypt_name }}_{{ ansible_date_time.date }}"
    keyfile: "/tmp/{{ crypt_name }}_{{ ansible_date_time.date }}"
    keyfile_len: 512

lvm:
  pv:
    - device: "/dev/mapper/{{ crypt_name }}"
  vg:
    - name: "{{ hostname }}_lvg01"
      pvresize: yes
      pvs:
        - "/dev/mapper/{{ crypt_name }}"
  lv:
    - name: root
      vg: "{{ hostname }}_lvg01"
      size: 32G
    - name: home
      vg: "{{ hostname }}_lvg01"
      size: 100%FREE

fs:
  - device: /dev/sda1
    fstype: vfat
  - device: "/dev/mapper/{{ hostname }}_lvg01-root"
    fstype: ext4
  - device: "/dev/mapper/{{ hostname }}_lvg01-home"
    fstype: ext4

root_part:
  device: /dev/mapper/{{ hostname }}_lvg01-root
  fstype: ext4

# I dont have a swap on my laptop since I dont want
# too many writes on my nvme flash. I have a script
# that warns me whenever I have filled up my RAM
# swap_part

mounts:
  - device: /dev/sda1
    path: "/boot"
    fstype: vfat
  - device: "/dev/mapper/{{ hostname }}_lvg01-home"
    path: "/home"
    fstype: ext4

initramfs_modules:
  - amdgpu
  - radeon

initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - modconf
  - block
  - sd-encrypt
  - sd-lvm2
  - filesystems
  - fsck

packages:
  # - cura
  - sof-firmware
  - intel-media-driver
  - intel-gpu-tools
  - xf86-video-amdgpu
  - libva-mesa-driver
  # - lib32-libva-mesa-driver
  # - networkmanager
  # - gnome

boot:
  device: /dev/sda1
  mount: /boot
  part: 1
  label: ArchLinux

cpu_manufacturer: amd
