---

hostname: 'graviton'

install_disk: "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3Z1NB0KA20685D"
part_postfix: "-part"

boot_vol_size: 512M
root_vol_size: 64G
var_vol_size: 16G
data_vol_size: 376G

nocrypt: false
nolvm: false
secureboot: false

initramfs_modules:
  - amdgpu
  - radeon

packages:
  - xf86-video-amdgpu
  - libva-mesa-driver
  - xf86-input-evdev
  - vulkan-radeon
  - virt-manager
  - qemu-base
  - dnsmasq

host_user_groups:
  - libvirt

cpu_manufacturer: amd
