---
- name: Configure hostname
  lineinfile:
    path: /etc/hostname
    line: "{{ hostname }}"
    create: yes

- name: Configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 644